//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_PANI.RoomHouse {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class KeyValuePairDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomHouse.IRoomHouseServices")]
    public interface IRoomHouseServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomHouseServices/GetRoomHouses", ReplyAction="http://tempuri.org/IRoomHouseServices/GetRoomHousesResponse")]
        Sistema_PANI.RoomHouse.KeyValuePairDTO[] GetRoomHouses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomHouseServices/GetRoomHouses", ReplyAction="http://tempuri.org/IRoomHouseServices/GetRoomHousesResponse")]
        System.Threading.Tasks.Task<Sistema_PANI.RoomHouse.KeyValuePairDTO[]> GetRoomHousesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomHouseServicesChannel : Sistema_PANI.RoomHouse.IRoomHouseServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomHouseServicesClient : System.ServiceModel.ClientBase<Sistema_PANI.RoomHouse.IRoomHouseServices>, Sistema_PANI.RoomHouse.IRoomHouseServices {
        
        public RoomHouseServicesClient() {
        }
        
        public RoomHouseServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomHouseServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomHouseServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomHouseServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sistema_PANI.RoomHouse.KeyValuePairDTO[] GetRoomHouses() {
            return base.Channel.GetRoomHouses();
        }
        
        public System.Threading.Tasks.Task<Sistema_PANI.RoomHouse.KeyValuePairDTO[]> GetRoomHousesAsync() {
            return base.Channel.GetRoomHousesAsync();
        }
    }
}
