//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_PANI.Address {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProvinceDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class ProvinceDTO : Sistema_PANI.Address.KeyValuePairDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Address.CountyDTO[] CountiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Address.CountyDTO[] Counties {
            get {
                return this.CountiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountiesField, value) != true)) {
                    this.CountiesField = value;
                    this.RaisePropertyChanged("Counties");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sistema_PANI.Address.CountyDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sistema_PANI.Address.ProvinceDTO))]
    public partial class KeyValuePairDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountyDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class CountyDTO : Sistema_PANI.Address.KeyValuePairDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Address.KeyValuePairDTO[] DistrictsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Address.KeyValuePairDTO[] Districts {
            get {
                return this.DistrictsField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictsField, value) != true)) {
                    this.DistrictsField = value;
                    this.RaisePropertyChanged("Districts");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Address.IAddressServices")]
    public interface IAddressServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressServices/GetProvince", ReplyAction="http://tempuri.org/IAddressServices/GetProvinceResponse")]
        Sistema_PANI.Address.ProvinceDTO[] GetProvince();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressServices/GetProvince", ReplyAction="http://tempuri.org/IAddressServices/GetProvinceResponse")]
        System.Threading.Tasks.Task<Sistema_PANI.Address.ProvinceDTO[]> GetProvinceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressServicesChannel : Sistema_PANI.Address.IAddressServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressServicesClient : System.ServiceModel.ClientBase<Sistema_PANI.Address.IAddressServices>, Sistema_PANI.Address.IAddressServices {
        
        public AddressServicesClient() {
        }
        
        public AddressServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sistema_PANI.Address.ProvinceDTO[] GetProvince() {
            return base.Channel.GetProvince();
        }
        
        public System.Threading.Tasks.Task<Sistema_PANI.Address.ProvinceDTO[]> GetProvinceAsync() {
            return base.Channel.GetProvinceAsync();
        }
    }
}
