//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_PANI.StateFile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class KeyValuePairDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StateFile.IStateFileServices")]
    public interface IStateFileServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateFileServices/GetStateFiles", ReplyAction="http://tempuri.org/IStateFileServices/GetStateFilesResponse")]
        Sistema_PANI.StateFile.KeyValuePairDTO[] GetStateFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStateFileServices/GetStateFiles", ReplyAction="http://tempuri.org/IStateFileServices/GetStateFilesResponse")]
        System.Threading.Tasks.Task<Sistema_PANI.StateFile.KeyValuePairDTO[]> GetStateFilesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStateFileServicesChannel : Sistema_PANI.StateFile.IStateFileServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StateFileServicesClient : System.ServiceModel.ClientBase<Sistema_PANI.StateFile.IStateFileServices>, Sistema_PANI.StateFile.IStateFileServices {
        
        public StateFileServicesClient() {
        }
        
        public StateFileServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StateFileServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateFileServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateFileServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sistema_PANI.StateFile.KeyValuePairDTO[] GetStateFiles() {
            return base.Channel.GetStateFiles();
        }
        
        public System.Threading.Tasks.Task<Sistema_PANI.StateFile.KeyValuePairDTO[]> GetStateFilesAsync() {
            return base.Channel.GetStateFilesAsync();
        }
    }
}
