//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_PANI.Adoption {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveAdoptionRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class SaveAdoptionRequestDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FamilyVisitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDKidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.SaveMarriageInformationDTO MarriageInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ParentsInterviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessDescripctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateFileIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllDocuments {
            get {
                return this.AllDocumentsField;
            }
            set {
                if ((this.AllDocumentsField.Equals(value) != true)) {
                    this.AllDocumentsField = value;
                    this.RaisePropertyChanged("AllDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FamilyVisit {
            get {
                return this.FamilyVisitField;
            }
            set {
                if ((this.FamilyVisitField.Equals(value) != true)) {
                    this.FamilyVisitField = value;
                    this.RaisePropertyChanged("FamilyVisit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDKid {
            get {
                return this.IDKidField;
            }
            set {
                if ((object.ReferenceEquals(this.IDKidField, value) != true)) {
                    this.IDKidField = value;
                    this.RaisePropertyChanged("IDKid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.SaveMarriageInformationDTO MarriageInformation {
            get {
                return this.MarriageInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.MarriageInformationField, value) != true)) {
                    this.MarriageInformationField = value;
                    this.RaisePropertyChanged("MarriageInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ParentsInterview {
            get {
                return this.ParentsInterviewField;
            }
            set {
                if ((this.ParentsInterviewField.Equals(value) != true)) {
                    this.ParentsInterviewField = value;
                    this.RaisePropertyChanged("ParentsInterview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessDescripction {
            get {
                return this.ProcessDescripctionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessDescripctionField, value) != true)) {
                    this.ProcessDescripctionField = value;
                    this.RaisePropertyChanged("ProcessDescripction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateFileId {
            get {
                return this.StateFileIdField;
            }
            set {
                if ((this.StateFileIdField.Equals(value) != true)) {
                    this.StateFileIdField = value;
                    this.RaisePropertyChanged("StateFileId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveMarriageInformationDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class SaveMarriageInformationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.SaveAddressDTO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.SavePersonDTO FatherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaritalStateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MarriageDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.SavePersonDTO MotherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomHouseIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.SaveAddressDTO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.SavePersonDTO Father {
            get {
                return this.FatherField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherField, value) != true)) {
                    this.FatherField = value;
                    this.RaisePropertyChanged("Father");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaritalStateId {
            get {
                return this.MaritalStateIdField;
            }
            set {
                if ((this.MaritalStateIdField.Equals(value) != true)) {
                    this.MaritalStateIdField = value;
                    this.RaisePropertyChanged("MaritalStateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MarriageDate {
            get {
                return this.MarriageDateField;
            }
            set {
                if ((this.MarriageDateField.Equals(value) != true)) {
                    this.MarriageDateField = value;
                    this.RaisePropertyChanged("MarriageDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.SavePersonDTO Mother {
            get {
                return this.MotherField;
            }
            set {
                if ((object.ReferenceEquals(this.MotherField, value) != true)) {
                    this.MotherField = value;
                    this.RaisePropertyChanged("Mother");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomHouseId {
            get {
                return this.RoomHouseIdField;
            }
            set {
                if ((this.RoomHouseIdField.Equals(value) != true)) {
                    this.RoomHouseIdField = value;
                    this.RaisePropertyChanged("RoomHouseId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveAddressDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class SaveAddressDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvinceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountyId {
            get {
                return this.CountyIdField;
            }
            set {
                if ((this.CountyIdField.Equals(value) != true)) {
                    this.CountyIdField = value;
                    this.RaisePropertyChanged("CountyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((this.DistrictIdField.Equals(value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvinceId {
            get {
                return this.ProvinceIdField;
            }
            set {
                if ((this.ProvinceIdField.Equals(value) != true)) {
                    this.ProvinceIdField = value;
                    this.RaisePropertyChanged("ProvinceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SavePersonDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class SavePersonDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.SaveJobInformationDTO JobInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondLastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((this.BirthDayField.Equals(value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.SaveJobInformationDTO JobInformation {
            get {
                return this.JobInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.JobInformationField, value) != true)) {
                    this.JobInformationField = value;
                    this.RaisePropertyChanged("JobInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonTypeId {
            get {
                return this.PersonTypeIdField;
            }
            set {
                if ((this.PersonTypeIdField.Equals(value) != true)) {
                    this.PersonTypeIdField = value;
                    this.RaisePropertyChanged("PersonTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName {
            get {
                return this.SecondLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondLastNameField, value) != true)) {
                    this.SecondLastNameField = value;
                    this.RaisePropertyChanged("SecondLastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveJobInformationDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class SaveJobInformationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActualPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AnualSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkerTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualPosition {
            get {
                return this.ActualPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualPositionField, value) != true)) {
                    this.ActualPositionField = value;
                    this.RaisePropertyChanged("ActualPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCompany {
            get {
                return this.AddressCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressCompanyField, value) != true)) {
                    this.AddressCompanyField = value;
                    this.RaisePropertyChanged("AddressCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AnualSalary {
            get {
                return this.AnualSalaryField;
            }
            set {
                if ((this.AnualSalaryField.Equals(value) != true)) {
                    this.AnualSalaryField = value;
                    this.RaisePropertyChanged("AnualSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkerTypeId {
            get {
                return this.WorkerTypeIdField;
            }
            set {
                if ((this.WorkerTypeIdField.Equals(value) != true)) {
                    this.WorkerTypeIdField = value;
                    this.RaisePropertyChanged("WorkerTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdoptionRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class AdoptionRequestDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FamilyVisitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDKidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.MarriageInformationDTO MarriageInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ParentsInterviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessDescripctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO StateFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllDocuments {
            get {
                return this.AllDocumentsField;
            }
            set {
                if ((this.AllDocumentsField.Equals(value) != true)) {
                    this.AllDocumentsField = value;
                    this.RaisePropertyChanged("AllDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FamilyVisit {
            get {
                return this.FamilyVisitField;
            }
            set {
                if ((this.FamilyVisitField.Equals(value) != true)) {
                    this.FamilyVisitField = value;
                    this.RaisePropertyChanged("FamilyVisit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDKid {
            get {
                return this.IDKidField;
            }
            set {
                if ((object.ReferenceEquals(this.IDKidField, value) != true)) {
                    this.IDKidField = value;
                    this.RaisePropertyChanged("IDKid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.MarriageInformationDTO MarriageInformation {
            get {
                return this.MarriageInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.MarriageInformationField, value) != true)) {
                    this.MarriageInformationField = value;
                    this.RaisePropertyChanged("MarriageInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ParentsInterview {
            get {
                return this.ParentsInterviewField;
            }
            set {
                if ((this.ParentsInterviewField.Equals(value) != true)) {
                    this.ParentsInterviewField = value;
                    this.RaisePropertyChanged("ParentsInterview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessDescripction {
            get {
                return this.ProcessDescripctionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessDescripctionField, value) != true)) {
                    this.ProcessDescripctionField = value;
                    this.RaisePropertyChanged("ProcessDescripction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO StateFile {
            get {
                return this.StateFileField;
            }
            set {
                if ((object.ReferenceEquals(this.StateFileField, value) != true)) {
                    this.StateFileField = value;
                    this.RaisePropertyChanged("StateFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarriageInformationDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class MarriageInformationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.AddressDTO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.PersonDTO FatherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO MaritalStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MarriageDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.PersonDTO MotherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO RoomHouseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.AddressDTO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.PersonDTO Father {
            get {
                return this.FatherField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherField, value) != true)) {
                    this.FatherField = value;
                    this.RaisePropertyChanged("Father");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO MaritalState {
            get {
                return this.MaritalStateField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStateField, value) != true)) {
                    this.MaritalStateField = value;
                    this.RaisePropertyChanged("MaritalState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MarriageDate {
            get {
                return this.MarriageDateField;
            }
            set {
                if ((this.MarriageDateField.Equals(value) != true)) {
                    this.MarriageDateField = value;
                    this.RaisePropertyChanged("MarriageDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.PersonDTO Mother {
            get {
                return this.MotherField;
            }
            set {
                if ((object.ReferenceEquals(this.MotherField, value) != true)) {
                    this.MotherField = value;
                    this.RaisePropertyChanged("Mother");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO RoomHouse {
            get {
                return this.RoomHouseField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomHouseField, value) != true)) {
                    this.RoomHouseField = value;
                    this.RaisePropertyChanged("RoomHouse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class KeyValuePairDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class AddressDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO ProvinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class PersonDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.JobInformationDTO[] JobInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO PersonTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondLastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((this.BirthDayField.Equals(value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.JobInformationDTO[] JobInformation {
            get {
                return this.JobInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.JobInformationField, value) != true)) {
                    this.JobInformationField = value;
                    this.RaisePropertyChanged("JobInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO PersonType {
            get {
                return this.PersonTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonTypeField, value) != true)) {
                    this.PersonTypeField = value;
                    this.RaisePropertyChanged("PersonType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName {
            get {
                return this.SecondLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondLastNameField, value) != true)) {
                    this.SecondLastNameField = value;
                    this.RaisePropertyChanged("SecondLastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobInformationDTO", Namespace="http://schemas.datacontract.org/2004/07/Adoption.Contract.DataContract")]
    [System.SerializableAttribute()]
    public partial class JobInformationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActualPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AnualSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sistema_PANI.Adoption.KeyValuePairDTO WorkerTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualPosition {
            get {
                return this.ActualPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualPositionField, value) != true)) {
                    this.ActualPositionField = value;
                    this.RaisePropertyChanged("ActualPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCompany {
            get {
                return this.AddressCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressCompanyField, value) != true)) {
                    this.AddressCompanyField = value;
                    this.RaisePropertyChanged("AddressCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AnualSalary {
            get {
                return this.AnualSalaryField;
            }
            set {
                if ((this.AnualSalaryField.Equals(value) != true)) {
                    this.AnualSalaryField = value;
                    this.RaisePropertyChanged("AnualSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sistema_PANI.Adoption.KeyValuePairDTO WorkerType {
            get {
                return this.WorkerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerTypeField, value) != true)) {
                    this.WorkerTypeField = value;
                    this.RaisePropertyChanged("WorkerType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Adoption.IAdoptionServices")]
    public interface IAdoptionServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/AddAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/AddAdoptionProcessResponse")]
        Sistema_PANI.Adoption.AdoptionRequestDTO AddAdoptionProcess(Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/AddAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/AddAdoptionProcessResponse")]
        System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO> AddAdoptionProcessAsync(Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/RemoveAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/RemoveAdoptionProcessResponse")]
        int RemoveAdoptionProcess(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/RemoveAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/RemoveAdoptionProcessResponse")]
        System.Threading.Tasks.Task<int> RemoveAdoptionProcessAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/UpdateAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/UpdateAdoptionProcessResponse")]
        Sistema_PANI.Adoption.AdoptionRequestDTO UpdateAdoptionProcess(int id, Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/UpdateAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/UpdateAdoptionProcessResponse")]
        System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO> UpdateAdoptionProcessAsync(int id, Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/GetadoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/GetadoptionProcessResponse")]
        Sistema_PANI.Adoption.AdoptionRequestDTO GetadoptionProcess(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/GetadoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/GetadoptionProcessResponse")]
        System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO> GetadoptionProcessAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/GetAllAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/GetAllAdoptionProcessResponse")]
        Sistema_PANI.Adoption.AdoptionRequestDTO[] GetAllAdoptionProcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdoptionServices/GetAllAdoptionProcess", ReplyAction="http://tempuri.org/IAdoptionServices/GetAllAdoptionProcessResponse")]
        System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO[]> GetAllAdoptionProcessAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdoptionServicesChannel : Sistema_PANI.Adoption.IAdoptionServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdoptionServicesClient : System.ServiceModel.ClientBase<Sistema_PANI.Adoption.IAdoptionServices>, Sistema_PANI.Adoption.IAdoptionServices {
        
        public AdoptionServicesClient() {
        }
        
        public AdoptionServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdoptionServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdoptionServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdoptionServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sistema_PANI.Adoption.AdoptionRequestDTO AddAdoptionProcess(Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest) {
            return base.Channel.AddAdoptionProcess(adoptionRequest);
        }
        
        public System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO> AddAdoptionProcessAsync(Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest) {
            return base.Channel.AddAdoptionProcessAsync(adoptionRequest);
        }
        
        public int RemoveAdoptionProcess(int id) {
            return base.Channel.RemoveAdoptionProcess(id);
        }
        
        public System.Threading.Tasks.Task<int> RemoveAdoptionProcessAsync(int id) {
            return base.Channel.RemoveAdoptionProcessAsync(id);
        }
        
        public Sistema_PANI.Adoption.AdoptionRequestDTO UpdateAdoptionProcess(int id, Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest) {
            return base.Channel.UpdateAdoptionProcess(id, adoptionRequest);
        }
        
        public System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO> UpdateAdoptionProcessAsync(int id, Sistema_PANI.Adoption.SaveAdoptionRequestDTO adoptionRequest) {
            return base.Channel.UpdateAdoptionProcessAsync(id, adoptionRequest);
        }
        
        public Sistema_PANI.Adoption.AdoptionRequestDTO GetadoptionProcess(int id) {
            return base.Channel.GetadoptionProcess(id);
        }
        
        public System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO> GetadoptionProcessAsync(int id) {
            return base.Channel.GetadoptionProcessAsync(id);
        }
        
        public Sistema_PANI.Adoption.AdoptionRequestDTO[] GetAllAdoptionProcess() {
            return base.Channel.GetAllAdoptionProcess();
        }
        
        public System.Threading.Tasks.Task<Sistema_PANI.Adoption.AdoptionRequestDTO[]> GetAllAdoptionProcessAsync() {
            return base.Channel.GetAllAdoptionProcessAsync();
        }
    }
}
